image: ubuntu

variables:
  GOVERSION: "1.10"

# Used to install the needed software in the container
before_script:
# Install all tools needed for the build
  - apt update
  - apt install wget -y
  - apt install curl -y
  - apt install make -y
  - apt install build-essential -y
# Install Go
  - wget https://dl.google.com/go/go$GOVERSION.linux-amd64.tar.gz
  - tar -C /usr/local -xzf go$GOVERSION.linux-amd64.tar.gz
  - export PATH=$PATH:/usr/local/go/bin
  - go env
# Install Nodejs (npm)
  - curl -sL https://deb.nodesource.com/setup_9.x | -E bash -
  - apt install nodejs -y
  - npm version

build:
  script: make build