image: ubuntu

variables:
  GO_VERSION: "1.10"
  GO_PATH: "/build/go"
  PROJECT_PATH: "/gitlab.com/ChristianAEDev"

# Used to install the needed software in the container
before_script:
  # This /builds/christian/worky" part of the folder is never needed. But for some reason GitLab
  # cd's into it at the end of the build. If it's not there the whole build fails.
  - mkdir -p /builds/christian/worky"
  - mkdir -p $GO_PATH/src/$PROJECT_PATH/builds/christian/worky -p
  - cd ..
  - mv worky $GO_PATH/src/$PROJECT_PATH
  - cd $GO_PATH/src/$PROJECT_PATH/worky
# Install all tools needed for the build
  - apt update
  - apt install wget -y
  - apt install curl -y
  - apt install make -y
  - apt install build-essential -y
  - apt install git -y
  - apt install zip -y
# Install Go
  - wget https://dl.google.com/go/go$GO_VERSION.linux-amd64.tar.gz
  - tar -C /usr/local -xzf go$GO_VERSION.linux-amd64.tar.gz
  - export GOPATH=/build/go
  - export PATH=$PATH:/usr/local/go/bin:$GO_PATH/bin
  - go version
  - go env
# Install dep (Go)
  - mkdir -p $GOPATH/bin
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
# Install Nodejs (npm)
  - curl -sL https://deb.nodesource.com/setup_9.x | bash -
  - apt install nodejs -y
  - npm version
# Install yarn
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
  - apt update
  - apt install yarn -y

build:
  script: make build