image: ubuntu

variables:
  GOVERSION: "1.10"

# Used to install the needed software in the container
before_script:
  - apt update
  - apt install wget -y
  - apt install make -y
  - wget https://dl.google.com/go/go$GOVERSION.linux-amd64.tar.gz
  - tar -C /usr/local -xzf go$GOVERSION.linux-amd64.tar.gz
  - export PATH=$PATH:/usr/local/go/bin
  - go env

build:
  script: make build